# Generated by Django 3.2.2 on 2021-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todolist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('docfile', models.FileField(upload_to='documents/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
